-- Additional feedback events with longer texts and varied dates
INSERT INTO feedback_events (text, timestamp, source, contract_value, is_actionable) VALUES
('We have been experiencing major issues with the dashboard export functionality over the past week. Every time we try to export our monthly reports, the system times out after about 30 seconds. This is causing significant delays in our reporting process and affecting our ability to share data with stakeholders. Our team has tried multiple browsers and cleared caches, but the problem persists. We are on an enterprise plan with a contract value of $150k annually and this is becoming a critical blocker for our operations. Please prioritize this as it is affecting our entire organization of 200+ users.', '2026-01-08T10:30:00Z', 'CS', 150000, NULL),

('I have been using your product for about 3 months now and I am generally satisfied with the features. However, I noticed that when I navigate between different sections of the application, there is a noticeable delay of 3-5 seconds. This happens especially when switching from the analytics view to the settings page. I am using Chrome on a MacBook Pro with a fast internet connection, so I do not think it is a hardware or network issue on my end. It would be great if you could look into optimizing the page transitions. I understand that there might be a lot of data loading, but perhaps implementing some kind of preloading or caching mechanism could help improve the user experience significantly.', '2026-01-09T14:15:00Z', 'Email', NULL, NULL),

('Our startup team of 8 people would love to use your platform, but the pricing structure is simply not feasible for us at our current stage. The basic plan lacks essential features like API access and custom integrations that we need, but the professional plan at $99 per user per month would cost us nearly $10k annually. For a bootstrapped startup, this is way beyond our budget. Many of your competitors offer startup-friendly pricing tiers or credits for early-stage companies. I think you are missing out on a significant market segment by not having a more accessible entry point. Would you consider creating a startup plan with reduced pricing but full feature access? We would be happy to provide testimonials and case studies in exchange for more reasonable pricing.', '2026-01-07T09:00:00Z', 'X', NULL, NULL),

('The onboarding experience for new team members is quite confusing and takes much longer than it should. When we added 5 new employees last week, each one took approximately 2-3 hours to get fully set up and understand how to use the basic features. The tutorial videos are helpful but they are outdated and do not reflect the current UI. The documentation is scattered across multiple pages and it is hard to find specific information. We ended up having to create our own internal wiki to guide new users through the setup process. For a product that markets itself as user-friendly and intuitive, this is disappointing. I would recommend creating a more streamlined onboarding flow with interactive walkthroughs, updated video content, and a centralized getting started guide.', '2026-01-06T16:45:00Z', 'Discord', NULL, NULL),

('I encountered a critical bug yesterday that caused us to lose about 4 hours of work. When editing a large document with multiple collaborators, the auto-save feature failed silently and we lost all changes made in the afternoon. There was no warning message or error notification, we only discovered the issue when we refreshed the page and realized our work was gone. This is extremely frustrating and unacceptable for a professional tool. We reached out to support immediately but were told that there is no way to recover the lost data. Moving forward, we need better error handling, more frequent auto-saves, and some kind of version history or backup system so that work is never permanently lost. This incident has shaken our confidence in the reliability of your platform.', '2026-01-15T11:20:00Z', 'CS', 85000, NULL),

('I would like to request a feature that I think would be incredibly valuable for many users. It would be great to have the ability to create custom workflows with conditional logic and automation rules. Right now, we have to manually perform many repetitive tasks that could easily be automated. For example, when a certain field reaches a specific threshold, we want to automatically trigger notifications, create tasks, and update related records. Many modern SaaS platforms offer this kind of workflow automation through a visual builder interface. Implementing this would save our team dozens of hours each week and make your product much more competitive in the market. I have spoken with several other customers who have expressed interest in similar functionality, so I believe there is strong demand for this feature.', '2026-01-05T13:30:00Z', 'GitHub', NULL, NULL),

('The mobile experience on iOS needs significant improvement. I frequently need to access the platform while traveling or away from my desk, but the mobile interface is barely usable. Buttons are too small and difficult to tap accurately, forms do not resize properly on smaller screens, and some features are completely inaccessible on mobile. I have an iPhone 14 Pro running the latest iOS version, so it is definitely not a device compatibility issue. The mobile web version seems like it was designed for desktop and then shrunk down without proper responsive design considerations. I would strongly recommend either building dedicated native mobile apps or at least ensuring the web version is fully responsive and touch-optimized. In 2026, mobile-first design should be a standard expectation.', '2026-01-12T08:45:00Z', 'CS', 95000, NULL),

('Performance has been terrible lately, especially during peak business hours between 9 AM and 5 PM EST. Pages take 10-15 seconds to load, searches time out frequently, and sometimes the application becomes completely unresponsive. We have a distributed team across multiple time zones and this is affecting productivity for everyone. When we contacted support, we were told that the system is experiencing high load and you are working on scaling infrastructure. However, this has been an ongoing issue for over a month now with no visible improvement. We are paying for a premium enterprise plan and expect consistent, reliable performance. If this continues, we may need to explore alternative solutions. Please provide a concrete timeline for when these performance issues will be resolved.', '2026-01-11T10:15:00Z', 'Email', 120000, NULL),

('I absolutely love the new dashboard redesign! The updated interface is clean, modern, and much more intuitive than the previous version. The color scheme is pleasant to look at and the improved navigation makes it easy to find what I need. Great work to the design team!', '2026-01-13T15:00:00Z', 'X', NULL, NULL),

('Our compliance team has raised concerns about data export capabilities. We need to be able to export all user data in a machine-readable format for GDPR compliance and audit purposes. Currently, the export function only provides PDF reports which are not suitable for our needs. We require CSV or JSON exports with complete data including all metadata, timestamps, and change history. Additionally, we need the ability to schedule automatic exports on a regular basis rather than manually triggering them each time. This is not just a nice-to-have feature but a legal requirement for us to continue using your platform. We operate in the EU and must be able to provide users with complete copies of their data within 30 days upon request. Please treat this as a high priority compliance issue.', '2026-01-04T12:00:00Z', 'CS', 200000, NULL),

('The API documentation needs major improvements. As a developer integrating your platform with our internal systems, I have found the API docs to be incomplete, outdated, and sometimes contradictory. Many endpoints are not documented at all, error responses are not clearly explained, and the example code snippets often do not work as written. I have had to spend hours experimenting and debugging to figure out how things actually work. The lack of a sandbox environment for testing API calls is also problematic. I would recommend conducting a thorough audit of your API documentation, adding more comprehensive examples, documenting all endpoints and parameters, and providing a test environment where developers can experiment safely without affecting production data. Good documentation is crucial for developer experience and adoption.', '2026-01-14T09:30:00Z', 'GitHub', NULL, NULL),

('We are experiencing a show-stopping bug with the authentication system. Several users have reported being randomly logged out in the middle of their work sessions, sometimes multiple times per day. When they try to log back in, they occasionally receive vague error messages about invalid credentials even though their username and password are correct. This seems to be related to session management or token expiration issues. It is incredibly disruptive to workflow and causing frustration among our team. We have tried clearing cookies and browser cache as suggested by your support team, but the problem continues. This needs to be investigated and fixed urgently as it is making the platform nearly unusable for affected users. We are considering putting our account on hold until this is resolved.', '2026-01-03T14:20:00Z', 'Discord', NULL, NULL),

('Thank you so much for the excellent customer support! Your team responded to my inquiry within 30 minutes and resolved my issue completely. Really appreciate the quick turnaround!', '2026-01-02T11:00:00Z', 'Email', NULL, NULL),

('I want to suggest adding a dark mode option to the interface. Many users, including myself, prefer dark themes especially when working late at night or in low-light environments. It reduces eye strain and is better for OLED screens. Most modern applications offer this as a standard feature and I think your users would really appreciate having the choice between light and dark modes. This could be implemented as a simple toggle in the user settings. I have seen many requests for this feature in your community forums so there is definitely demand for it.', '2026-01-01T16:00:00Z', 'X', NULL, NULL),

('Our organization is looking for better team collaboration features. Currently, there is no built-in way for team members to comment on shared documents, mention colleagues in discussions, or track who made specific changes. We have resorted to using external communication tools like Slack to discuss work that is happening in your platform, which creates friction and context switching. It would be incredibly valuable to have native collaboration features such as inline comments, @mentions, activity feeds showing team member actions, and threaded discussions. This would make your platform more of a central hub for teamwork rather than just a tool we use individually. Real-time collaboration is becoming table stakes for modern productivity software.', '2026-01-16T10:00:00Z', 'CS', 175000, NULL);
